### ISSUE TITLE
サーバー構築に用いる言語確定

### ISSUE THREAD

**Issue by leonis0** [gakufu0/gakufu#2]
# 概要
 * サーバー側も自作の必要性がありそうなのでその時に用いる言語の選択
# 以下現状あがっている案
## python & Django
 * 書きやすさならNo.1(?)
 * リクエスト数が増えてくると処理が遅すぎる可能性が....
## Ruby on Rails
 * 名前しか知らない
## Go言語
 * 処理速度はある程度出る模様
 * 並列処理が簡単だから複数のクライアント捌くときは便利(？)
## ShellScript
 * mkb先生の一押し

### かなり迷ってる状態なのでアイデアください...

**Comment by sylba2050** [comment]
go言語で
